### ISSUE TITLE
adminpanel

### ISSUE THREAD

**Issue by etekumoses** [himanshuchauhan981/E-commerce-app-using-flutter-and-firebase#43]
please could you please share with us how we can add products to firestore

**Comment by wafahas** [comment]
please could you please share with us how we can add products to firestore

**Comment by himanshuchauhan981** [comment]
I have added steps in the [readme](https://github.com/himanshuchauhan981/E-commerce-app-using-flutter-and-firebase/blob/master/README.md) file.
