### ISSUE TITLE
Admin panel issue: while adding items.

### ISSUE THREAD

**Issue by chirag42** [himanshuchauhan981/E-commerce-app-using-flutter-and-firebase#57]
After clicking LOAD DATA button in Admin panel, it is not adding anything in firebase. I tried to print the categories variable in adminServices.dart file. There's a minor error which I'm sure you can identify and fix that. It would be much helpful if u do this at the earliest.

**Comment by himanshuchauhan981** [comment]
Hie, I tried to recreate this scenario and admin panel was working well. It even created sample data in firebase. You need to check your firebase firestore connection to app. Since this admin panel issue is working, so I am closing this issue.
