### ISSUE TITLE
I cant see the products

### ISSUE THREAD

**Issue by LuisGassier** [himanshuchauhan981/E-commerce-app-using-flutter-and-firebase#69]
I can´t load the data

**Comment by himanshuchauhan981** [comment]
@LuisGassier Kindly show error when you hit button from admin screen.

**Comment by LuisGassier** [comment]
![image](https://user-images.githubusercontent.com/56460777/116211725-b9e0e500-a709-11eb-9e70-1fdd3157bf8f.png)
![image](https://user-images.githubusercontent.com/56460777/116211821-d67d1d00-a709-11eb-9abe-c1c92c9baab8.png)

**Comment by LuisGassier** [comment]
![image](https://user-images.githubusercontent.com/56460777/116212166-29ef6b00-a70a-11eb-8960-9441e2abe026.png)

**Comment by himanshuchauhan981** [comment]
@LuisGassier kindly check your firebase connection. Also check firestore data
